# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d6b0fa92-30d4-4a98-a2a4-ba984c9fc8e6";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/d6b0fa92-30d4-4a98-a2a4-ba984c9fc8e6";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d6b0fa92-30d4-4a98-a2a4-ba984c9fc8e6";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/272C-7D79";
      fsType = "vfat";
    };

  fileSystems."/mnt/backup" =
    { device = "/dev/mapper/backup";
      fsType = "ext4";
      encrypted = {
        blkDev = "/dev/disk/by-uuid/e321cc57-8b4c-425a-97ba-4547a005713d";
        enable = true;
        label = "backup";
        keyFile = "/mnt-root/root/.backup-key";
      };
    };

  fileSystems."/mnt/sandisk" =
    { device = "/dev/disk/by-uuid/ec551948-21e6-4b0f-86c4-41a6132c7827";
      fsType = "btrfs";
    };

  fileSystems."/home/dominik/Games" =
    { device = "/mnt/sandisk/Games";
      options = [ "bind" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # GPU features
  hardware.opengl.driSupport = true;
  hardware.opengl.driSupport32Bit = true;
}
